### ISSUE TITLE
Blender Error

### ISSUE THREAD

**Issue by jkznst** [MichaelRamamonjisoa/SyntheT-Less#1]
Hello, thanks for your work! I ran your code but something about blender went wrong. Here is the main error:

OUTPATH: multi_objects/2
Traceback (most recent call last):
  File "/xxx/SyntheT-Less/render_sample_multi_object.py", line 403, in <module>
    use_normals=args.normals, use_depth=args.depth, use_obj_instances=True, num_objects=num_objects)
  File "./blender_utils.py", line 19, in set_cycles
    prefs = bpy.context.user_preferences
AttributeError: 'Context' object has no attribute 'user_preferences'
Blender quit

I followed your commands to set up the environment (Blender 2.80). Could you help me solve this problem? Thanks.

**Comment by jkznst** [comment]
The command I use is:
python3 call_blender_multi.py --blender_path ./blender/ --dtd-rootdir ./DTD/ --models_path ./models_cad/ --cpus 8 --size 10 --cuda 0

**Comment by MichaelRamamonjisoa** [comment]
Hi, thank you for your interest!
I think there is indeed an error. When searching for it, I found this thread:
https://github.com/AlansCodeLog/blender-debugger-for-vscode/issues/11#issuecomment-453880417

Apparently, the problem comes from the update to blender 2.80.

Could you try to replace line 19 in blender_utils.py https://github.com/MichaelRamamonjisoa/SyntheT-Less/blob/46a5ff714ca8052d3707bc32f61c8cdc09b13312/blender_utils.py#L19
`prefs = bpy.context.user_preferences`

with 
`prefs = bpy.context.preferences`

?
If it still does not work, could you try to install blender 2.79 instead of 2.80? 
Please let me know how this goes, as I will update my code accordingly.

**Comment by demianhj** [comment]
the dataset link that you provided seems to be not available,could you please check it out? If it's out of date, can you provide another link to download the data? @MichaelRamamonjisoa

**Comment by MichaelRamamonjisoa** [comment]
> 
> 
> the dataset link that you provided seems to be not available,could you please check it out? If it's out of date, can you provide another link to download the data? @MichaelRamamonjisoa

Hi, sorry for the inconvenience, I'll try to host it somewhere else in the next days.

**Comment by demianhj** [comment]
> > the dataset link that you provided seems to be not available,could you please check it out? If it's out of date, can you provide another link to download the data? @MichaelRamamonjisoa
> 
> Hi, sorry for the inconvenience, I'll try to host it somewhere else in the next days.

Hope to see that, thank you very much :)

**Comment by MichaelRamamonjisoa** [comment]
> > > the dataset link that you provided seems to be not available,could you please check it out? If it's out of date, can you provide another link to download the data? @MichaelRamamonjisoa
> > 
> > 
> > Hi, sorry for the inconvenience, I'll try to host it somewhere else in the next days.
> 
> Hope to see that, thank you very much :)

Thank you for your patience, the download link has been updated.
